# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T8saYo9bdPSI3B8vjSWvUcUc4JtzF5dF
"""

#9
import matplotlib.pyplot as plt
import numpy as np
y=np.array([3,8,1,10])
x=np.array([5,6,9,12])
plt.plot (x,y, marker='o')
plt.show()

#14
import matplotlib.pyplot as plt
import numpy as np
y=np.array([3,8,1,10])
x=np.array([5,6,9,12])
plt.plot (x,y, marker='o', ms=20, mec='r')
plt.show()

#13
import matplotlib.pyplot as plt
import numpy as np
y=np.array([3,8,1,10])
x=np.array([5,6,9,12])
plt.plot (x,y, marker='o', ms=20)
plt.show()

#15
import matplotlib.pyplot as plt
import numpy as np
x1=np.array([0,1,2,3])
y1=np.array([3,4,1,6])
x2=np.array([0,1,2,3])
y2=np.array([5,6,2,9])
plt.plot(x1,y1,x2,y2)
plt.show()

#16
import matplotlib.pyplot as plt
import numpy as np
x1=np.array([0,1,2,3])
y1=np.array([3,4,1,6])
plt.plot(x1,y1,marker='o',ms=20,mfc='r')
plt.show()

#27

import matplotlib.pyplot as plt
import numpy as np
x1=np.array([0,1,2,3])
y1=np.array([3,9,1,6])
plt.scatter(x1,y1,)
plt.show()

#28
import matplotlib.pyplot as plt
import numpy as np
x1=np.array([0,1,2,3,8,9,5])
y1=np.array([3,9,1,6,6,8,7])
plt.scatter(x1,y1,color='red')
x1=np.array([1,8,2,6,7,4,5])
y1=np.array([3,9,8,6,9,2,7])
plt.scatter(x1,y1,color='green')

plt.show()

#29
import matplotlib.pyplot as plt
import numpy as np
x1=np.array([0,1,2,3,8,6])
y1=np.array([3,9,1,6,8,7])
mycolor=['red','green','purple','lime','aqua','yellow']
plt.scatter(x1,y1,color=mycolor)
plt.show()

#30
import matplotlib.pyplot as plt
import numpy as np
x1=np.array([0,1,2,3,8,6])
y1=np.array([3,9,1,6,8,7])
mycolor=['red','green','purple','lime','aqua','yellow']
size=[10,60,120,200,20,60]
plt.scatter(x1,y1,color=mycolor,s=size)
plt.show()

#33import matplotlib.pyplot as plt
import numpy as np
x= np.array(['614','613','510'])
y=np.array([15,10,5])
plt.bar(x,y)
plt.show()

#36
import matplotlib.pyplot as plt
import numpy as np
x= np.array([1, 2,6,8])
plt.pie(x)
plt.show()

#37
import matplotlib.pyplot as plt
import numpy as np
x= np.array([1, 2,6,8])
mylabels=['C#','C++','Phyton','HTML']
plt.pie(x, labels=mylabels)
plt.show()

#39
import matplotlib.pyplot as plt
import numpy as np
x= np.array([1, 2,6,8])
mylabels=['C#','C++','Phyton','HTML']
myexplode=[0,0,0.2,0]
plt.pie(x, labels=mylabels,startangle=90,explode=myexplode)
plt.show()

#41
import matplotlib.pyplot as plt
import numpy as np
x= np.array([1, 2,6,8])
mylabels=['C#','C++','Phyton','HTML']
mycolors=["yellow","hotpink","green","b"]
myexplode=[0,0,0.2,0]
plt.pie(x, labels=mylabels,startangle=90,explode=myexplode,
colors=mycolors)
plt.show()

#43
import matplotlib.pyplot as plt
import numpy as np
x= np.array([35,25,50,14])
mylabels=['C#','C++','Phyton','HTML']
plt.pie(x,labels=mylabels)
plt.legend(title='Four Fruits:')
plt.show()

#44
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm


plt.style.use('classic')

X = np.arange(-5, 4, 0.25)
Y = np.arange(-5, 5, 0.25)
X, Y = np.meshgrid(X, Y)
R = np.sqrt(X**2 + Y**2)
Z = np.sin(R)
fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
ax.plot_surface(X, Y, Z, vmin=Z.min() * 2, cmap=cm.Blues)
ax.set(xticklabels=[],
       yticklabels=[],
       zticklabels=[])
plt.show()

#45
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm
import math

plt.style.use('classic')

X = np.arange(-4,3,2)
Y = np.arange(-5,5,4)
X, Y = np.meshgrid(X, Y)
X = X * np.cos(X)*(np.cos(Y)+1)
Y = X * np.sin(X)*(np.cos(Y)+1)
Z = X * np.sin(Y)

fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
ax.plot_surface(X, Y, Z, vmin=Z.min() * 2, cmap=cm.Blues)
ax.set(xticklabels=[],
       yticklabels=[],
       zticklabels=[])
plt.show()

#7
import matplotlib.pyplot as plt
import numpy as np
x= np.array([1, 2,6,8])
y=np.array([3,8,1,10])
plt.plot(x,y)
plt.show()



import matplotlib.pyplot as plt
import numpy as np
x= np.array([0, 6])
y= np.array([0, 250])
plt.plot(x, y)
plt.show()